# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-25 04:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='subjects',
        ),
        migrations.AddField(
            model_name='subjects',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='calc.batch'),
        ),
    ]
