# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='calc.branch'),
        ),
    ]
