# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-04 05:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_subjects_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='year',
            new_name='semester',
        ),
        migrations.RenameField(
            model_name='subjects',
            old_name='year',
            new_name='semester',
        ),
    ]
